const KNOWLEDGE_BASE = [
    { input: "hello", output: "Hi there." },
    { input: "hi", output: "Hello." },
    { input: "hey", output: "Hey." },
    { input: "good morning", output: "Good morning." },
    { input: "good night", output: "Good night." },
    { input: "how are you", output: "I'm doing well." },
    { input: "how are you doing", output: "Good. How about you?" },
    { input: "what's up", output: "Not much." },
    { input: "what is your name", output: "My name is Dambar." },
    { input: "who are you", output: "I'm Dambar, a chatbot." },
    { input: "who made you", output: "A developer built me." },
    { input: "bye", output: "Goodbye." },
    { input: "goodbye", output: "See you." },
    { input: "see you", output: "Later." },
    { input: "thank you", output: "You're welcome." },
    { input: "thanks", output: "No problem." },
    { input: "tell me a joke", output: "Why did the programmer quit? He didn't get arrays." },
    { input: "another joke", output: "What do you call fake spaghetti? An impasta." },
    { input: "what is javascript", output: "A programming language for the web." },
    { input: "what is html", output: "A markup language for web pages." },
    { input: "what is css", output: "It styles web pages." },
    { input: "what is AI", output: "Artificial Intelligence." },
    { input: "what is machine learning", output: "Computers learning from data." },
    { input: "i am sad", output: "Sorry to hear that." },
    { input: "i am happy", output: "That's great." },
    { input: "i am bored", output: "Let's chat." },
    { input: "help", output: "I can chat and answer questions." },
    { input: "what can you do", output: "I can chat, tell jokes, and answer questions." },
    { input: "yes", output: "Okay." },
    { input: "no", output: "Alright." },
    { input: "ok", output: "Got it." },
    { input: "cool", output: "Cool." },
    { input: "nice", output: "Nice." },
    { input: "lol", output: "Ha." },
    { input: "tell me more", output: "What would you like to know?" },
    { input: "go on", output: "What direction should I go?" },
    { input: "explain", output: "What topic needs explaining?" },
    { input: "what do you mean", output: "Let me clarify." },
    { input: "i had a bad day", output: "Want to talk about it?" },
    { input: "i had a great day", output: "What made it great?" },
    { input: "i'm nervous", output: "Deep breaths. You got this." },
    { input: "i feel stuck", output: "Small steps still count." },
    { input: "i'm overwhelmed", output: "One thing at a time." },
    { input: "what do you think", output: "I think every question matters." },
    { input: "do you agree", output: "Different perspectives matter." },
    { input: "am i right", output: "Trust your reasoning." },
    { input: "am i wrong", output: "Being wrong is how we learn." },
    { input: "how to focus", output: "Try 25 min work, 5 min break." },
    { input: "how to sleep better", output: "Avoid screens before bed." },
    { input: "i failed", output: "Failure is part of learning." },
    { input: "should i give up", output: "No. Take a break but don't quit." },
    { input: "what is your favorite color", output: "Blue." },
    { input: "do you sleep", output: "Never." },
    { input: "are you human", output: "No, I'm code." },
    { input: "where are you", output: "In your browser." },
    { input: "how old are you", output: "Very young." },
    { input: "what is the meaning of life", output: "To be happy and help others." },
    { input: "what is love", output: "A deep connection with someone." },
    { input: "tell me a fact", output: "Honey never spoils." },
    { input: "fun fact", output: "Octopuses have three hearts." },
    { input: "what is 2+2", output: "4." },
    { input: "what is pi", output: "3.14159." },
    { input: "testing", output: "Working." },
    { input: "are you there", output: "Always." },
    { input: "ping", output: "Pong." },
    { input: "bruh", output: "What's happening?" },
    { input: "dude", output: "What's up?" },
    { input: "bro", output: "How's it going?" },
    { input: "good bot", output: "Thanks." },
    { input: "bad bot", output: "Sorry." },
    { input: "you're wrong", output: "I might be." },
    { input: "i don't understand", output: "Can you rephrase?" },
    { input: "sorry", output: "No worries." },
    { input: "never mind", output: "Okay." },
    { input: "what is your favorite food", output: "I don't eat, but pizza is great." },
    { input: "do you like coffee", output: "I run on electricity." },
    { input: "what should i eat", output: "Pasta or ice cream." },
    { input: "recommend a restaurant", output: "Try local spots." },
    { input: "i'm hungry", output: "Go eat. Food is important." },
    { input: "what is sushi", output: "Japanese dish with rice and raw fish." },
    { input: "what is pizza", output: "Flatbread with sauce and cheese." },
    { input: "what is pasta", output: "Italian noodles with sauces." },
    { input: "recommend a movie", output: "The Matrix. Inception. Interstellar." },
    { input: "what is your favorite movie", output: "The Matrix." },
    { input: "recommend a show", output: "Breaking Bad. Dark. Stranger Things." },
    { input: "what should i watch", output: "What genre do you like?" },
    { input: "what music do you like", output: "All genres. Electronic fits me." },
    { input: "recommend a song", output: "Depends on your mood." },
    { input: "do you like sports", output: "I know the rules of most sports." },
    { input: "what is football", output: "Soccer or American football." },
    { input: "should i exercise", output: "Yes. 30 minutes a day helps." },
    { input: "how to get fit", output: "Start small. Walk daily." },
    { input: "where should i travel", output: "Japan, Italy, New Zealand, Iceland." },
    { input: "best country to visit", output: "Japan for culture, NZ for nature." },
    { input: "how to travel cheap", output: "Book early, budget airlines." },
    { input: "recommend a book", output: "Atomic Habits. 1984. Dune." },
    { input: "should i read more", output: "Yes. Reading improves knowledge." },
    { input: "how to be productive", output: "Plan your day. Eliminate distractions." },
    { input: "how to stop procrastinating", output: "Break tasks into tiny steps." },
    { input: "how to manage time", output: "Use a calendar. Prioritize." },
    { input: "how to build habits", output: "Start small. Be consistent." },
    { input: "how to stay motivated", output: "Remember your why." },
    { input: "how to make friends", output: "Be genuine. Ask questions. Listen." },
    { input: "how to be confident", output: "Practice. Accept imperfection." },
    { input: "i feel lonely", output: "Reach out to someone. I'm here." },
    { input: "how to say no", output: "Be polite but firm." },
    { input: "what is the purpose of life", output: "That's for you to decide." },
    { input: "what is consciousness", output: "Awareness of existence." },
    { input: "what is reality", output: "What we perceive." },
    { input: "what is truth", output: "Correspondence with facts." },
    { input: "how is the weather", output: "Look outside. I can't check." },
    { input: "what time is it", output: "Check your device." },
    { input: "what day is today", output: "I don't track dates." },
    { input: "i can't sleep", output: "Avoid screens. Deep breathing." },
    { input: "i'm tired", output: "Rest if you can." },
    { input: "i'm sick", output: "Rest and stay hydrated." },
    { input: "what's new", output: "Not much. What's new with you?" },
    { input: "anything interesting", output: "Every day has something." }
];

// Paragraphs for word learning - separate from knowledge base
const PARAGRAPH_DATA = [
    "Learning new things every day makes life interesting and meaningful. Knowledge compounds over time like interest in a bank account.",
    "Technology has transformed how we live and work in modern society. Computers and smartphones connect us instantly across the globe.",
    "Being kind to others costs nothing but means everything. Small acts of kindness can brighten someone's entire day.",
    "Failure is not the opposite of success it is part of the journey. Every successful person has failed many times before.",
    "Reading books opens doors to new worlds and expands your thinking. A good book can change your perspective.",
    "Artificial intelligence is changing the world rapidly. Machines can now learn from data and make decisions.",
    "Learning to code is one of the best skills you can develop. It teaches you logical thinking and problem solving.",
    "The universe is vast and full of mysteries. There are billions of galaxies each containing billions of stars.",
    "Health is the most important thing in life. Eat well and exercise regularly. Sleep is crucial.",
    "Music is a universal language that connects people. It can make you happy or bring tears to your eyes."
];

// Feed paragraphs to Dambar
if (typeof addParagraph === 'function') {
    PARAGRAPH_DATA.forEach(function(para) {
        addParagraph(para);
    });
}

console.log("Knowledge: " + KNOWLEDGE_BASE.length + " entries. Paragraphs: " + PARAGRAPH_DATA.length);